# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2047954fd2d002fd8dcbc04922d963f97b64d90c55d7ada89b5dc07492dbd45d7e87b1ffdeb6abf11a7d02c5729acd919a684723d23162aae5e69f4b09494db

test:
  secret_key_base: 3ae6d73234890cbe71a6e9e6c67786d44684247316d12ce72e9faad0f165b34c7c051264e4f0f63d66cd38c1dba4e84413a3b2f809bec3f8b79e34ada6f9b86e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
